#!/usr/bin/env python3
"""Regenerate tests/fixture_cubins.hpp from real ptxas output.

Steps (Linux/CI):
  pip install nvidia-cuda-nvcc-cu12
  ptxas -arch=sm_75 probe.ptx -o probe_sm_75.cubin   # etc for sm_89, sm_120
  python3 tools/make_fixtures.py probe_sm_75.cubin probe_sm_89.cubin probe_sm_120.cubin

The probe PTX is embedded in the generated header so the cubins are
reproducible.  Fixtures matter because they pin the *real* e_flags words
produced by the CUDA 12.9 assembler: 0x004B054B (sm_75), 0x00590559
(sm_89), 0x06007802 (sm_120).  Driver-era cubins use the 0x0600SS04 style
that the reference project's verified SM86 stamp mirrors.
"""
from __future__ import annotations

import pathlib
import struct
import sys

PTX = """\
.version 8.0
.target sm_75
.address_size 64
.visible .entry nvs30_probe(.param .u64 p0)
{
    .reg .b64 %rd<4>;
    .reg .b32 %r<4>;
    ld.param.u64 %rd1, [p0];
    mov.u32 %r1, 42;
    cvta.to.global.u64 %rd2, %rd1;
    st.global.u32 [%rd2], %r1;
    ret;
}
"""


def elf_flags(path: pathlib.Path) -> int:
    data = path.read_bytes()
    assert data[:4] == b"\x7fELF" and len(data) > 0x34, f"not an ELF cubin: {path}"
    return struct.unpack_from("<I", data, 0x30)[0]


def emit(out: list[str], name: str, data: bytes) -> None:
    out.append(f"inline constexpr unsigned char kCubin_{name}[] = {{")
    for i in range(0, len(data), 16):
        out.append(",".join("0x%02X" % b for b in data[i : i + 16]) + ",")
    out.append("};")
    out.append(f"inline constexpr std::size_t kCubin_{name}_size = {len(data)};")
    out.append("")


def main() -> None:
    if len(sys.argv) == 2 and sys.argv[1] == "--ptx":
        sys.stdout.write(PTX)
        return
    if len(sys.argv) != 4:
        raise SystemExit(__doc__)
    inputs = dict(zip(("sm75", "sm89", "sm120"), map(pathlib.Path, sys.argv[1:4])))
    root = pathlib.Path(__file__).resolve().parents[1]
    out = [
        "// Auto-generated by tools/make_fixtures.py -- do not edit by hand.",
        "// Real cubins produced by ptxas (CUDA 12.9) from the PTX embedded below.",
        "#pragma once",
        "#include <cstddef>",
        "namespace fixture {",
        "",
    ]
    for key, path in inputs.items():
        data = path.read_bytes()
        out.append(f"// {key}: {len(data)} bytes, e_flags=0x{elf_flags(path):08X}")
        emit(out, key, data)
    out.append("// PTX source (compiled per-arch with: ptxas -arch=sm_75|sm_89|sm_120):")
    for line in PTX.splitlines():
        out.append(f"// {line}")
    out.append("}  // namespace fixture")
    (root / "tests" / "fixture_cubins.hpp").write_text("\n".join(out) + "\n")
    print("wrote tests/fixture_cubins.hpp")


if __name__ == "__main__":
    main()
